using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<ProtoId<JukeboxPrototype>>? OnQueueSong;
    public event Action? OnClearQueue;
    public event Action<bool>? OnShuffleToggled;
    public event Action<bool>? OnRepeatSongToggled;
    public event Action<int>? OnVolumeChanged;
    public event Action<float>? SetTime;

    private EntityUid? _audio;

    private float _lockTimer;
    private ProtoId<JukeboxPrototype>? _selectedSongId;
    private bool _suppressUiEvents;

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            _selectedSongId = juke;
            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += args =>
        {
            OnStopPressed?.Invoke();
        };

        QueueButton.OnPressed += _ =>
        {
            if (_selectedSongId is { } selected)
            {
                OnQueueSong?.Invoke(selected);
            }
        };

        ClearQueueButton.OnPressed += _ =>
        {
            OnClearQueue?.Invoke();
        };

        ShuffleToggle.OnToggled += args =>
        {
            if (_suppressUiEvents)
                return;

            OnShuffleToggled?.Invoke(args.Pressed);
        };

        RepeatSongToggle.OnToggled += args =>
        {
            if (_suppressUiEvents)
                return;

            OnRepeatSongToggled?.Invoke(args.Pressed);
        };

        VolumeSlider.OnValueChanged += args =>
        {
            var level = (int) MathF.Round(args.Value);
            UpdateVolumeLabel(level);

            if (_suppressUiEvents)
                return;

            OnVolumeChanged?.Invoke(level);
        };

        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
        SetVolumeLevel(JukeboxComponent.DefaultVolumeLevel);
    }

    public JukeboxMenu(AudioSystem audioSystem)
    {
        _audioSystem = audioSystem;
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        MusicList.Clear();

        foreach (var entry in jukeboxProtos)
        {
            MusicList.AddItem(entry.Name, metadata: entry.ID);
        }
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }

    public void SetQueue(IEnumerable<ProtoId<JukeboxPrototype>> queue, IPrototypeManager prototypeManager)
    {
        QueueList.Clear();

        foreach (var queuedSong in queue)
        {
            if (prototypeManager.Resolve(queuedSong, out var song))
            {
                QueueList.AddItem(song.Name, metadata: queuedSong);
            }
            else
            {
                QueueList.AddItem(queuedSong, metadata: queuedSong);
            }
        }
    }

    public void SetShuffleState(bool enabled)
    {
        _suppressUiEvents = true;
        ShuffleToggle.Pressed = enabled;
        _suppressUiEvents = false;
    }

    public void SetRepeatSongState(bool enabled)
    {
        _suppressUiEvents = true;
        RepeatSongToggle.Pressed = enabled;
        _suppressUiEvents = false;
    }

    public void SetVolumeLevel(int level)
    {
        var clamped = Math.Clamp(level, JukeboxComponent.MinVolumeLevel, JukeboxComponent.MaxVolumeLevel);
        _suppressUiEvents = true;
        VolumeSlider.SetValueWithoutEvent(clamped);
        _suppressUiEvents = false;
        UpdateVolumeLabel(clamped);
    }

    public void SetSelectedSong(string name, float length)
    {
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $"00:00 / 00:00";
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }

    private void UpdateVolumeLabel(int level)
    {
        VolumeValue.Text = Loc.GetString("jukebox-menu-volume-value", ("level", level));
    }
}
