using Content.Client.Guidebook.Richtext;
//using Content.Shared.Chemistry.Reagent;
using Content.Shared.Botany;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding a plant nutrient into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuidePlantNutrientGroupEmbed : BoxContainer, IDocumentTag
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;


    public GuidePlantNutrientGroupEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        var prototypes = _prototype.EnumeratePrototypes<PlantNutrientPrototype>().OrderBy(p => p.LocalizedName);
        foreach (var nutrient in prototypes)
        {
            var embed = new GuidePlantNutrientEmbed(nutrient);
            GroupContainer.AddChild(embed);
        }

        control = this;
        return true;
    }
}
