using Content.Client.Guidebook.Richtext;
using Content.Shared.Chemistry.Reagent;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reaction;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding a reagent into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideReagentGroupEmbed : BoxContainer, IDocumentTag
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    public GuideReagentGroupEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.reagent_group");
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideReagentGroupEmbed(string group) : this()
    {
        if (group == "Precipitate")
        {
            var prototypes = _prototype.EnumeratePrototypes<ReactionPrototype>()
                .Where(p => !p.Source && p.Effects.Length >= 1)
                .OrderBy(p => p.Priority)
                .ThenBy(p => p.Products.Count)
                .ToList();
            foreach (var reagent in prototypes)
            {
                var embed = new GuideReagentEmbed(reagent);
                GroupContainer.AddChild(embed);
            }
        }
        else
        {
            var prototypes = _prototype.EnumeratePrototypes<ReagentPrototype>()
            .Where(p => p.Group.Equals(group)).OrderBy(p => p.LocalizedName);
            foreach (var reagent in prototypes)
            {
                var embed = new GuideReagentEmbed(reagent);
                GroupContainer.AddChild(embed);
            }
        }
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Group", out var group))
        {
            _sawmill.Error("Reagent group embed tag is missing group argument");
            return false;
        }

        if (group == "Precipitate")
        {
            Dictionary<string, GuideReagentEmbed> precipitateDict = new Dictionary<string, GuideReagentEmbed>();
            var prototypes = _prototype.EnumeratePrototypes<ReactionPrototype>()
                .Where(p => !p.Source && p.Effects.Length >= 1)
                .OrderBy(p => p.Priority)
                .ThenBy(p => p.Products.Count)
                .ToList();
            foreach (var reagent in prototypes)
            {
                if (reagent.Effects.Length < 1)
                    continue;
                IEnumerable<Shared.EntityEffects.Effects.EntitySpawning.SpawnEntity> spawnEvents = reagent.Effects.OfType<Shared.EntityEffects.Effects.EntitySpawning.SpawnEntity>();
                if (spawnEvents.Count() == 0)
                    continue;
                var spawnId = _prototype.Index<EntityPrototype>(spawnEvents.First().Entity).Name;
                if (precipitateDict.ContainsKey(spawnId))
                    continue;
                precipitateDict.Add(spawnId, new GuideReagentEmbed(reagent));
            }
            foreach (var key in precipitateDict.Keys.OrderBy(k => k))
            {
                GroupContainer.AddChild(precipitateDict[key]);
            }
        }
        else
        {
            var prototypes = _prototype.EnumeratePrototypes<ReagentPrototype>()
            .Where(p => p.Group.Equals(group)).OrderBy(p => p.LocalizedName);
            foreach (var reagent in prototypes)
            {
                var embed = new GuideReagentEmbed(reagent);
                GroupContainer.AddChild(embed);
            }
        }

        control = this;
        return true;
    }
}
