using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Localizations;
using Content.Shared.EntityEffects.Effects.Botany;
using Content.Shared.Botany;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuidePlantNutrientSource : BoxContainer, ISearchableControl
{
    private static readonly ProtoId<MixingCategoryPrototype> DefaultMixingCategory = "DummyPlantOsmosis";

    private readonly IPrototypeManager _protoMan;

    public GuidePlantNutrientSource(IPrototypeManager protoMan)
    {
        RobustXamlLoader.Load(this);
        _protoMan = protoMan;
    }

    public GuidePlantNutrientSource(ReagentPrototype reagent, IPrototypeManager protoMan, IEntitySystemManager sysMan, string prod = "") : this(protoMan)
    {
        Container container = SourcesContainer;
        SetNutrients(reagent, ref container, protoMan);
        Container productContainer = NutrientsContainer;
        var nutrients = GetNutrients(reagent);
        if (prod != "")
        {
            nutrients.Add(prod, 1);
        }
        SetNutrients(nutrients, ref productContainer, protoMan, false);

        var mixingCategories = new List<MixingCategoryPrototype> { protoMan.Index(DefaultMixingCategory) };
        SetMixingCategory(mixingCategories, sysMan);
    }

    public GuidePlantNutrientSource(EntityPrototype prototype,
        Solution solution,
        IReadOnlyList<ProtoId<MixingCategoryPrototype>> categories,
        IPrototypeManager protoMan,
        IEntitySystemManager sysMan) : this(protoMan)
    {
        var icon = sysMan.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(prototype).GetFrame(RsiDirection.South, 0);
        var entContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            Children =
            {
                new TextureRect
                {
                    Texture = icon
                }
            }
        };
        var nameLabel = new RichTextLabel();
        nameLabel.SetMarkup(Loc.GetString("guidebook-reagent-sources-ent-wrapper", ("name", prototype.Name)));
        entContainer.AddChild(nameLabel);
        SourcesContainer.AddChild(entContainer);

        Container productContainer = NutrientsContainer;
        SetNutrients(solution.Contents, ref productContainer, protoMan, false);
        SetMixingCategory(categories, sysMan);
    }

    public GuidePlantNutrientSource(GasPrototype prototype,
        IReadOnlyList<ProtoId<MixingCategoryPrototype>> categories,
        IPrototypeManager protoMan,
        IEntitySystemManager sysMan) : this(protoMan)
    {
        var label = new RichTextLabel();
        label.SetMarkup(Loc.GetString("guidebook-reagent-sources-gas-wrapper",
            ("name", Loc.GetString(prototype.Name).ToLower())));

        SourcesContainer.Visible = true;
        SourcesContainer.AddChild(label);

        if (prototype.Nutrient != null)
        {
            var quantity = new Dictionary<string, FixedPoint2>
            {
                { prototype.Nutrient, prototype.NutrientAmount }
            };
            Container productContainer = NutrientsContainer;
            SetNutrients(quantity, ref productContainer, protoMan, false);
        }
        SetMixingCategory(categories, sysMan);
    }

    private Dictionary<string, FixedPoint2> GetNutrients(ReagentPrototype reagent)
    {
        Dictionary<string, FixedPoint2> nutrients = new();
        foreach (var effect in reagent.PlantMetabolisms)
        {
            if (effect is PlantAdjustNutrient adjustNutrient)
                nutrients.Add(adjustNutrient.Nutrient, adjustNutrient.Amount);
        }
        return nutrients;
    }

    private void SetNutrients(List<ReagentQuantity> reagents, ref Container container, IPrototypeManager protoMan, bool addLinks = true)
    {
        var amounts = new Dictionary<string, FixedPoint2>();
        foreach (var (reagent, quantity) in reagents)
        {
            amounts.Add(reagent.Prototype, quantity);
        }
        SetNutrients(amounts, ref container, protoMan, addLinks);
    }

    private void SetNutrients(
        ReagentPrototype reagent,
        ref Container container,
        IPrototypeManager protoMan,
        bool addLinks = true)
    {
        var amounts = new Dictionary<string, FixedPoint2>();
        amounts.Add(reagent.ID, 1);
        SetNutrients(amounts, ref container, protoMan, addLinks);
    }

    [PublicAPI]
    private void SetNutrients(
        Dictionary<ProtoId<MixingCategoryPrototype>, ReactantPrototype> reactants,
        ref Container container,
        IPrototypeManager protoMan,
        bool addLinks = true)
    {
        var amounts = new Dictionary<string, FixedPoint2>();
        foreach (var (reagent, reactantPrototype) in reactants)
        {
            amounts.Add(reagent, reactantPrototype.Amount);
        }
        SetNutrients(amounts, ref container, protoMan, addLinks);
    }

    private void SetNutrients(Dictionary<string, FixedPoint2> reagents, ref Container container, IPrototypeManager protoMan, bool addLinks = true)
    {
        foreach (var (product, amount) in reagents.OrderByDescending(p => p.Value))
        {
            var msg = new FormattedMessage();
            var label = new GuidebookRichPrototypeLink();
            if (protoMan.HasIndex<ReagentPrototype>(product))
            {
                var productProto = protoMan.Index<ReagentPrototype>(product);
                msg.AddMarkupOrThrow(Loc.GetString("guidebook-reagent-recipes-reagent-display",
                    ("reagent", productProto.LocalizedName), ("ratio", amount)));
                if (addLinks)
                    label.LinkedPrototype = productProto;
            }
            else if (protoMan.HasIndex<PlantNutrientPrototype>(product))
            {
                var productProto = protoMan.Index<PlantNutrientPrototype>(product);
                msg.AddMarkupOrThrow(Loc.GetString("guidebook-reagent-recipes-reagent-display",
                    ("reagent", productProto.LocalizedName), ("ratio", amount)));
                if (addLinks)
                    label.LinkedPrototype = productProto;
            }
            else
            {
                var productProto = protoMan.Index<EntityPrototype>(product);
                msg.AddMarkupOrThrow(Loc.GetString("guidebook-reagent-recipes-reagent-display",
                    ("reagent", productProto.Name), ("ratio", amount)));
                if (addLinks)
                    label.LinkedPrototype = productProto;
            }
            label.SetMessage(msg);
            container.AddChild(label);
        }
        container.Visible = true;
    }

    private void SetMixingCategory(IReadOnlyList<ProtoId<MixingCategoryPrototype>> mixingCategories, IEntitySystemManager sysMan)
    {
        var foo = new List<MixingCategoryPrototype>();
        foreach (var cat in mixingCategories)
        {
            foo.Add(_protoMan.Index(cat));
        }
        SetMixingCategory(foo, sysMan);
    }

    private void SetMixingCategory(IReadOnlyList<MixingCategoryPrototype> mixingCategories, IEntitySystemManager sysMan)
    {
        if (mixingCategories.Count == 0)
            return;

        // only use the first one for the icon.
        if (mixingCategories.First() is { } primaryCategory)
        {
            MixTexture.Texture = sysMan.GetEntitySystem<SpriteSystem>().Frame0(primaryCategory.Icon);
        }

        var mixingVerb = ContentLocalizationManager.FormatList(mixingCategories
            .Select(p => Loc.GetString(p.VerbText)).ToList());

        var text = Loc.GetString("guidebook-plant-nutrients-source-info", ("verb", mixingVerb));

        MixLabel.SetMarkup(text);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }
}
